// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "Fios-JNRON"
#define SECRET_PASS "visas2249old884tag"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a13s8kmdddvqm1-ats.iot.us-east-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICgTCCAWmgAwIBAgIUZgfBPkqOOIkRIUJQy6vWsENevbQwDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIxMDMxOTIxMjc1
MFoXDTQ5MTIzMTIzNTk1OVowETEPMA0GA1UEAxMGR3NyQmVlMFkwEwYHKoZIzj0C
AQYIKoZIzj0DAQcDQgAEBnVT2CfSbG6e/pwTTb4EVQxczuFujAaM6QVuHPals9ck
q7OO33js1xBapUkDuZ2bdZzyOwGv+p11YmncJs6gAqNgMF4wHwYDVR0jBBgwFoAU
eV/ZOzYLFd6qoAFI8GxqdJSRnEcwHQYDVR0OBBYEFG8o3I9KntlW9NvaXYG0haQh
U4OpMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUA
A4IBAQC6p2WBF8WdFAkKEQDnZd8VOQMVFuyfhcMe0MyFDl6QiP9CmoaALof7Mv4o
j+tSk28VDbxYQqj5H59RcltRrnOxJUplJnmEWkORFkrYjiVuR9NDbE57k855QCIF
/WTJvH0cemH+NeoPMVUCzxWx17Bi38oYd7Y75x+IcVVDmqV970MqiYsCetUFmiJ5
/51pMKJ5SMNjhNNITUCdbnso1lB01jXvPvpdn6lToZzizbw3LRfr9UarFqiSJe84
HGikISIvyVISoxVWQ2KgNUol1u6x2rAbMPJ+G1pTjiCOwp+FVaavJj/Qdo3jGcvf
4PRmMwpXR3DRkM/eEtXiBXGEu+9s
-----END CERTIFICATE-----
)";
